// Account model.
//
// An Account is owned by a User and holds the authoritative balance for that
// user. All monetary values are stored as INTEGER PESEWAS (100 pesewas = 1 GHS)
// to avoid IEEE-754 floating-point drift (Requirement 15.1). The schema enforces
// the monetary integer-range invariant (Property 11): every stored balance is a
// non-negative safe integer within [0, 9_999_999_999_999].
//
// The `accountNumber` is a unique, indexed, fixed-length 10-digit numeric string
// (Requirement 1.2). Account numbers are generated by the service layer using the
// generateAccountNumber utility; this model only enforces the format/uniqueness
// invariants.
import mongoose from 'mongoose';

const { Schema, model } = mongoose;

export const ACCOUNT_STATUS = Object.freeze({
  ACTIVE: 'Active',
  FROZEN: 'Frozen',
  DISABLED: 'Disabled',
});

// Inclusive bounds for a stored balance, in integer pesewas (Requirement 15.1).
export const MIN_BALANCE_PESEWAS = 0;
export const MAX_BALANCE_PESEWAS = 9_999_999_999_999;

const accountSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    accountNumber: {
      type: String,
      required: true,
      unique: true,
      index: true,
      // Exactly 10 numeric digits (Requirement 1.2).
      match: [/^\d{10}$/, 'accountNumber must be exactly 10 numeric digits'],
    },
    accountType: {
      type: String,
      default: 'Savings',
    },
    // Integer pesewas. The atomic conditional `$inc` update in bankService is the
    // primary non-negativity guard; these schema validators are a defense-in-depth
    // backstop enforcing the monetary integer-range invariant (Property 11).
    balance: {
      type: Number,
      default: 0,
      min: [MIN_BALANCE_PESEWAS, 'balance must not be negative'],
      max: [MAX_BALANCE_PESEWAS, 'balance exceeds the maximum allowed pesewas'],
      validate: {
        validator: Number.isInteger,
        message: 'balance must be an integer number of pesewas',
      },
    },
    currency: {
      type: String,
      default: 'GHS',
    },
    status: {
      type: String,
      enum: Object.values(ACCOUNT_STATUS),
      default: ACCOUNT_STATUS.ACTIVE,
      index: true,
    },
  },
  { timestamps: true }
);

const Account = model('Account', accountSchema);

export default Account;
